version: '3.8'

services:
  metrikcorp-v2:
    container_name: metrikcorp-v2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    restart: always
    networks:
      - web

networks:
  web:
    external: true
